name: HTML/CSS Validate & JS Unit Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ "main", "new-user&delete-post-E2E" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install jest
        run: npm install --save-dev jest babel-jest @babel/core @babel/preset-env puppeteer jest-puppeteer
             npm install --save-dev jest-environment-jsdom
             npm install --save-dev fake-indexeddb

      # Validate HTML/CSS in source/
      - name: HTMLCheck
        run: uname -a
      - name: HTML5Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.1.1
        with:
            root: source/
            log_level: INFO
            css: true

      # Run unit tests with jest
      - name: JSCheck
        # Must pass HTMLCheck before testing js
        run: |
          # cd ./source/scripts
          # ./testPrep.sh
          npm test new-user-delete-E2E.test.js